### ISSUE TITLE
NaxaneTheme.css background color clashes with link color

### ISSUE THREAD

**Issue by TheArchiteck** [HearToWear/BlackCon#3]
The NaxaneTheme.css' background color is too similar a color to the default link color. Placing a link on the background causes the link to become difficult to read.

The easiest way to solve this would be to change either the background color, or the link color. I recommend the background color, because it's already a little dark as it is.

**Comment by HearToWear** [comment]
The problem is that it always look like someone took a piss on the webpage, so colours suck and turn out a lot uglier than they do on the color picker. Not sure why this happens, but maybe it's because wikidot still writes their websites in XHTML, which is really outdated. I commited a few changes that might fix this problem, but colours are looking a bit mucky.

**Comment by HearToWear** [comment]
I pushed an update as an attempt to fix the colours. Tell me what you think.

**Comment by TheArchiteck** [comment]
The previous background color definitely looked cleaner overall. Perhaps we should revert to a slight variant of that background color, and up the lightness for the link color instead.

I'll be fiddling with it.

**Comment by TheArchiteck** [comment]
I've pushed forward a "Color Re-do and Sidebar Tweaks" commit. This issue is officially fixed.
